# GENERATED by tools/gen_makefile_deps.py -- do not edit by hand.
# Regenerate after adding/removing a module, a use statement, or
# an include. CI runs the generator with --check.

MODULE_SRCS := atm/atm_lib.f90 atm/atm_table_lib.f90 atm/atmstruct_lib.f90 atm/envstruct_lib.f90 core/burn_lib.f90 core/envint_lib.f90 core/monte_carlo.f90 core/observables_lib.f90 core/stitched_model.f90 core/stop_conditions.f90 core/yrec_capi.f90 core/yrec_reset.f90 eos/eos_lib.f90 eos/eos_mixture_lib.f90 eos/mhd_eos_lib.f90 eos/opal_eos_lib.f90 eos/scv_eos_lib.f90 eos/yale_eos_lib.f90 io/controls_lib.f90 io/luout_lib.f90 io/run_log.f90 io/yrec_output.f90 kap/conductive_table_lib.f90 kap/kap_lib.f90 kap/opacity_table_lib.f90 net/net_lib.f90 numerics/intpar_lib.f90 numerics/numerics_lib.f90 rotation/rotation_scratch_lib.f90 state/controls_sync_lib.f90 state/phys_const_lib.f90 state/star_info_lib.f90

# order-only rules: each object waits for the module objects
# whose .mod files it reads
atm/atm_lib.o: | atm/atm_table_lib.o state/star_info_lib.o
atm/atmstruct_lib.o: | state/star_info_lib.o
atm/envstruct_lib.o: | state/star_info_lib.o
atm/tables/alfilein.o: | atm/atm_table_lib.o io/luout_lib.o state/star_info_lib.o
atm/tables/alsurfp.o: | atm/atm_table_lib.o io/luout_lib.o numerics/numerics_lib.o state/star_info_lib.o
atm/tables/altabinit.o: | atm/atm_table_lib.o io/luout_lib.o
atm/tables/kcsurfp.o: | atm/atm_table_lib.o io/luout_lib.o numerics/numerics_lib.o
atm/tables/surfp.o: | atm/atm_table_lib.o io/luout_lib.o numerics/numerics_lib.o
atm/test/test_atm.o: | atm/atm_lib.o atm/atm_table_lib.o eos/scv_eos_lib.o io/luout_lib.o kap/opacity_table_lib.o state/star_info_lib.o
core/atmosphere_derivs.o: | atm/atm_table_lib.o eos/eos_lib.o kap/kap_lib.o state/phys_const_lib.o state/star_info_lib.o
core/burn_lib.o: | io/luout_lib.o net/net_lib.o numerics/numerics_lib.o rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
core/check_solar_calibration.o: | io/luout_lib.o state/star_info_lib.o
core/check_star_calibration.o: | io/luout_lib.o state/phys_const_lib.o state/star_info_lib.o
core/envelope_derivs.o: | eos/eos_lib.o kap/kap_lib.o state/phys_const_lib.o state/star_info_lib.o
core/envint_lib.o: | atm/atm_table_lib.o atm/atmstruct_lib.o atm/envstruct_lib.o eos/eos_lib.o io/luout_lib.o io/run_log.o kap/kap_lib.o numerics/intpar_lib.o numerics/numerics_lib.o state/phys_const_lib.o state/star_info_lib.o
core/evolve_step.o: | core/burn_lib.o core/observables_lib.o core/stitched_model.o core/stop_conditions.o io/luout_lib.o io/yrec_output.o net/net_lib.o state/phys_const_lib.o state/star_info_lib.o
core/henyey_coefficients.o: | core/burn_lib.o eos/eos_lib.o kap/kap_lib.o net/net_lib.o rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
core/henyey_iterate.o: | eos/yale_eos_lib.o io/luout_lib.o io/run_log.o state/phys_const_lib.o state/star_info_lib.o
core/henyey_solve.o: | state/star_info_lib.o
core/monte_carlo.o: | io/luout_lib.o state/phys_const_lib.o state/star_info_lib.o
core/neutrino_flux_table.o: | core/burn_lib.o io/luout_lib.o state/phys_const_lib.o state/star_info_lib.o
core/observables_lib.o: | eos/eos_lib.o state/phys_const_lib.o state/star_info_lib.o
core/read_starting_model.o: | atm/atm_lib.o atm/envstruct_lib.o core/envint_lib.o core/stitched_model.o eos/eos_lib.o eos/scv_eos_lib.o eos/yale_eos_lib.o io/luout_lib.o kap/kap_lib.o kap/opacity_table_lib.o state/phys_const_lib.o state/star_info_lib.o
core/rebuild_envelope.o: | atm/atm_lib.o atm/envstruct_lib.o core/envint_lib.o eos/yale_eos_lib.o state/phys_const_lib.o state/star_info_lib.o
core/run_yrec.o: | core/monte_carlo.o core/stop_conditions.o core/yrec_reset.o io/luout_lib.o io/run_log.o io/yrec_output.o net/net_lib.o state/phys_const_lib.o state/star_info_lib.o
core/shell_physics.o: | eos/eos_lib.o kap/kap_lib.o numerics/numerics_lib.o rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
core/star_setup.o: | core/monte_carlo.o state/star_info_lib.o
core/stitched_model.o: | atm/atmstruct_lib.o atm/envstruct_lib.o core/envint_lib.o state/phys_const_lib.o state/star_info_lib.o
core/stop_conditions.o: | io/luout_lib.o state/star_info_lib.o
core/surfbc.o: | atm/atm_lib.o atm/atm_table_lib.o core/envint_lib.o io/luout_lib.o io/run_log.o state/phys_const_lib.o state/star_info_lib.o
core/turnover_timescale.o: | core/stitched_model.o numerics/numerics_lib.o state/phys_const_lib.o state/star_info_lib.o
core/yrec_capi.o: | state/star_info_lib.o
core/yrec_reset.o: | rotation/rotation_scratch_lib.o state/star_info_lib.o
eos/eos_lib.o: | eos/eos_mixture_lib.o eos/opal_eos_lib.o eos/scv_eos_lib.o eos/yale_eos_lib.o io/luout_lib.o state/phys_const_lib.o state/star_info_lib.o
eos/eqstat.o: | eos/eos_mixture_lib.o eos/scv_eos_lib.o io/luout_lib.o state/phys_const_lib.o state/star_info_lib.o
eos/mhd/meqos.o: | eos/mhd_eos_lib.o io/luout_lib.o state/star_info_lib.o
eos/mhd/mhdpx.o: | eos/mhd_eos_lib.o io/luout_lib.o
eos/mhd/mhdpx1.o: | eos/mhd_eos_lib.o io/luout_lib.o numerics/numerics_lib.o
eos/mhd/mhdpx2.o: | eos/mhd_eos_lib.o numerics/numerics_lib.o
eos/mhd/mhdst.o: | eos/mhd_eos_lib.o
eos/mhd/mhdtbl.o: | state/star_info_lib.o
eos/mu.o: | eos/eos_mixture_lib.o state/phys_const_lib.o
eos/opal/eqbound.o: | eos/opal_eos_lib.o
eos/opal/eqbound01.o: | eos/opal_eos_lib.o
eos/opal/eqbound06.o: | eos/opal_eos_lib.o
eos/opal/esac.o: | eos/opal_eos_lib.o io/luout_lib.o
eos/opal/esac01.o: | eos/opal_eos_lib.o io/luout_lib.o
eos/opal/esac06.o: | eos/opal_eos_lib.o io/luout_lib.o
eos/opal/oeqos.o: | eos/opal_eos_lib.o io/luout_lib.o state/phys_const_lib.o state/star_info_lib.o
eos/opal/oeqos01.o: | eos/opal_eos_lib.o io/luout_lib.o state/phys_const_lib.o state/star_info_lib.o
eos/opal/oeqos06.o: | eos/opal_eos_lib.o io/luout_lib.o state/phys_const_lib.o state/star_info_lib.o
eos/opal/quad.o: | eos/opal_eos_lib.o
eos/opal/quadeos01.o: | eos/opal_eos_lib.o
eos/opal/quadeos06.o: | eos/opal_eos_lib.o
eos/opal/radsub.o: | eos/opal_eos_lib.o
eos/opal/radsub01.o: | eos/opal_eos_lib.o
eos/opal/radsub06.o: | eos/opal_eos_lib.o
eos/opal/readco.o: | eos/opal_eos_lib.o io/luout_lib.o state/star_info_lib.o
eos/opal/readcoeos01.o: | eos/opal_eos_lib.o io/luout_lib.o state/star_info_lib.o
eos/opal/readcoeos06.o: | eos/opal_eos_lib.o io/luout_lib.o state/star_info_lib.o
eos/opal/rhoofp.o: | eos/opal_eos_lib.o
eos/opal/rhoofp01.o: | eos/opal_eos_lib.o
eos/opal/rhoofp06.o: | eos/opal_eos_lib.o
eos/opal/t6rinteos01.o: | eos/opal_eos_lib.o io/luout_lib.o
eos/opal/t6rinteos06.o: | eos/opal_eos_lib.o io/luout_lib.o
eos/opal/t6rinterp.o: | eos/opal_eos_lib.o io/luout_lib.o
eos/scv/eqscve.o: | eos/eos_mixture_lib.o eos/scv_eos_lib.o numerics/numerics_lib.o state/phys_const_lib.o
eos/scv/eqscvg.o: | eos/scv_eos_lib.o numerics/numerics_lib.o state/phys_const_lib.o state/star_info_lib.o
eos/scv/scv_envelope_table.o: | eos/scv_eos_lib.o numerics/numerics_lib.o state/phys_const_lib.o state/star_info_lib.o
eos/test/test_eos.o: | eos/eos_lib.o eos/scv_eos_lib.o eos/yale_eos_lib.o io/luout_lib.o kap/opacity_table_lib.o state/star_info_lib.o
eos/yale/fully_ionized_eos.o: | eos/yale_eos_lib.o io/luout_lib.o state/phys_const_lib.o
eos/yale/saha_eos.o: | io/luout_lib.o state/phys_const_lib.o
io/equal_to_model.o: | numerics/numerics_lib.o state/star_info_lib.o
io/model_to_equal.o: | numerics/numerics_lib.o rotation/rotation_scratch_lib.o state/star_info_lib.o
io/print_allard_tables.o: | atm/atm_table_lib.o io/luout_lib.o
io/read_controls.o: | atm/atm_table_lib.o eos/eos_lib.o eos/scv_eos_lib.o eos/yale_eos_lib.o io/controls_lib.o io/luout_lib.o io/yrec_output.o kap/opacity_table_lib.o numerics/intpar_lib.o state/controls_sync_lib.o state/phys_const_lib.o state/star_info_lib.o
io/read_mod_model.o: | io/luout_lib.o state/star_info_lib.o
io/read_model2.o: | state/star_info_lib.o
io/read_yrec7.o: | state/star_info_lib.o
io/run_log.o: | io/luout_lib.o state/star_info_lib.o
io/write_fgong_pulse.o: | state/phys_const_lib.o state/star_info_lib.o
io/write_gsm_pulse.o: | io/luout_lib.o
io/write_gyre_pulse.o: | state/phys_const_lib.o state/star_info_lib.o
io/write_mod_model.o: | io/luout_lib.o io/run_log.o state/star_info_lib.o
io/write_output_headers.o: | io/luout_lib.o state/star_info_lib.o
io/yrec_output.o: | core/stitched_model.o io/luout_lib.o io/run_log.o state/phys_const_lib.o state/star_info_lib.o
kap/alex06/alex06tab.o: | kap/opacity_table_lib.o numerics/numerics_lib.o
kap/alex06/getalex06.o: | kap/opacity_table_lib.o numerics/numerics_lib.o state/phys_const_lib.o
kap/alex06/readalex06.o: | kap/opacity_table_lib.o state/star_info_lib.o
kap/alex94/alex94_fixed_z_table.o: | kap/opacity_table_lib.o numerics/numerics_lib.o
kap/alex94/alex94_interp3d.o: | kap/opacity_table_lib.o numerics/numerics_lib.o state/phys_const_lib.o
kap/alex94/alex94_surface_table.o: | kap/opacity_table_lib.o numerics/numerics_lib.o
kap/alex94/read_alex94_tables.o: | io/luout_lib.o kap/opacity_table_lib.o state/star_info_lib.o
kap/conductive/condopacp.o: | kap/conductive_table_lib.o state/star_info_lib.o
kap/kap_lib.o: | io/luout_lib.o kap/opacity_table_lib.o state/star_info_lib.o
kap/kurucz90/build_kurucz_splines.o: | kap/opacity_table_lib.o numerics/numerics_lib.o state/star_info_lib.o
kap/kurucz90/kurucz.o: | io/luout_lib.o kap/opacity_table_lib.o numerics/numerics_lib.o
kap/kurucz90/kurucz2.o: | io/luout_lib.o kap/opacity_table_lib.o numerics/numerics_lib.o
kap/kurucz90/read_kurucz_tables.o: | kap/opacity_table_lib.o state/star_info_lib.o
kap/laol89/gtlaol.o: | io/luout_lib.o kap/opacity_table_lib.o numerics/numerics_lib.o
kap/laol89/gtlaol2.o: | io/luout_lib.o kap/opacity_table_lib.o numerics/numerics_lib.o
kap/laol89/gtpurz.o: | io/luout_lib.o kap/opacity_table_lib.o numerics/numerics_lib.o
kap/laol89/rdlaol.o: | eos/yale_eos_lib.o io/luout_lib.o kap/opacity_table_lib.o state/star_info_lib.o
kap/laol89/rdzlaol.o: | io/luout_lib.o kap/opacity_table_lib.o
kap/laol89/sulaol.o: | kap/opacity_table_lib.o numerics/numerics_lib.o state/star_info_lib.o
kap/laol89/zsulaol.o: | kap/opacity_table_lib.o numerics/numerics_lib.o
kap/opal92/opal92_interp2d.o: | kap/opacity_table_lib.o numerics/numerics_lib.o
kap/opal92/opal92_interp2d_z2.o: | kap/opacity_table_lib.o numerics/numerics_lib.o
kap/opal92/opal92_interp3d.o: | kap/opacity_table_lib.o numerics/numerics_lib.o
kap/opal92/opal92_interp3d_z2.o: | kap/opacity_table_lib.o numerics/numerics_lib.o
kap/opal92/opal92_surface_table.o: | kap/opacity_table_lib.o numerics/numerics_lib.o state/star_info_lib.o
kap/opal92/opal92_table_prep.o: | kap/opacity_table_lib.o numerics/numerics_lib.o state/star_info_lib.o
kap/opal92/read_opal92_tables.o: | kap/opacity_table_lib.o state/star_info_lib.o
kap/opal95/getopal95.o: | kap/opacity_table_lib.o numerics/numerics_lib.o state/star_info_lib.o
kap/opal95/ll95tbl.o: | io/luout_lib.o kap/opacity_table_lib.o state/star_info_lib.o
kap/opal95/opal95_fixed_z_table.o: | kap/opacity_table_lib.o numerics/numerics_lib.o
kap/opal95/opal95_interp2d.o: | kap/opacity_table_lib.o
kap/opal95/opal95_interp3d.o: | kap/opacity_table_lib.o
kap/opal95/opal95_interp4d.o: | kap/opacity_table_lib.o
kap/opal95/opal95_surface_table.o: | kap/opacity_table_lib.o numerics/numerics_lib.o
kap/setupopac.o: | kap/opacity_table_lib.o state/star_info_lib.o
kap/surfopac.o: | state/star_info_lib.o
kap/test/test_kap.o: | eos/scv_eos_lib.o io/luout_lib.o kap/kap_lib.o kap/opacity_table_lib.o state/star_info_lib.o
mixing/burn_mix_extrapolated.o: | rotation/rotation_scratch_lib.o state/star_info_lib.o
mixing/burn_settle_mix.o: | core/burn_lib.o net/net_lib.o state/star_info_lib.o
mixing/compute_scale_height.o: | eos/eos_lib.o state/phys_const_lib.o state/star_info_lib.o
mixing/find_convection_zones.o: | io/luout_lib.o state/star_info_lib.o
mixing/homogenize_convection_zones.o: | state/star_info_lib.o
mixing/mix.o: | core/burn_lib.o io/luout_lib.o io/run_log.o net/net_lib.o rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
mixing/overshoot_boundaries.o: | io/luout_lib.o state/phys_const_lib.o state/star_info_lib.o
mixing/rotmix.o: | io/luout_lib.o rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
mixing/semiconvection.o: | eos/eos_lib.o io/luout_lib.o kap/kap_lib.o state/phys_const_lib.o state/star_info_lib.o
mixing/solve_composition.o: | io/luout_lib.o numerics/numerics_lib.o state/star_info_lib.o
mixing/temperature_gradients.o: | eos/eos_lib.o io/luout_lib.o kap/kap_lib.o state/phys_const_lib.o state/star_info_lib.o
net/net_lib.o: | state/phys_const_lib.o state/star_info_lib.o
net/test/test_net.o: | core/burn_lib.o eos/scv_eos_lib.o io/controls_lib.o io/luout_lib.o kap/opacity_table_lib.o net/net_lib.o state/star_info_lib.o
numerics/numerics_lib.o: | io/luout_lib.o numerics/intpar_lib.o state/star_info_lib.o
rotation/am_convective_regions.o: | state/star_info_lib.o
rotation/enforce_rotation_profile.o: | state/phys_const_lib.o state/star_info_lib.o
rotation/equal_spaced_grid.o: | numerics/numerics_lib.o rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
rotation/evolve_angular_momentum.o: | core/burn_lib.o net/net_lib.o rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
rotation/microdiff/gravitational_settling.o: | io/luout_lib.o numerics/numerics_lib.o rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
rotation/microdiff/gravitational_settling_setup.o: | io/luout_lib.o rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
rotation/microdiff/implicit_diffusion_coeffs.o: | state/star_info_lib.o
rotation/microdiff/lax_wendroff_step1.o: | rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
rotation/microdiff/lax_wendroff_step2.o: | rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
rotation/microdiff/microdiff.o: | state/star_info_lib.o
rotation/microdiff/microdiff_coefficients.o: | state/phys_const_lib.o state/star_info_lib.o
rotation/microdiff/microdiff_etm.o: | numerics/numerics_lib.o state/star_info_lib.o
rotation/microdiff/microdiff_mte.o: | numerics/numerics_lib.o state/star_info_lib.o
rotation/microdiff/microdiff_run.o: | io/luout_lib.o numerics/numerics_lib.o state/phys_const_lib.o state/star_info_lib.o
rotation/microdiff/microdiff_setup.o: | io/luout_lib.o state/phys_const_lib.o state/star_info_lib.o
rotation/microdiff/thoul_diffusion.o: | numerics/numerics_lib.o
rotation/omega_from_j.o: | state/star_info_lib.o
rotation/rotation_scratch_lib.o: | state/star_info_lib.o
rotation/seculr/am_advection_diffusion_coeffs.o: | rotation/rotation_scratch_lib.o state/star_info_lib.o
rotation/seculr/am_diffusion_coeffs.o: | rotation/rotation_scratch_lib.o state/star_info_lib.o
rotation/seculr/am_transport_grid.o: | numerics/numerics_lib.o rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
rotation/seculr/check_angular_momentum.o: | io/luout_lib.o rotation/rotation_scratch_lib.o state/star_info_lib.o
rotation/seculr/check_composition.o: | io/luout_lib.o rotation/rotation_scratch_lib.o state/star_info_lib.o
rotation/seculr/circulation_velocities.o: | rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
rotation/seculr/composition_diffusion_coeffs.o: | state/star_info_lib.o
rotation/seculr/composition_grid.o: | numerics/numerics_lib.o rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
rotation/seculr/compute_quadrupole.o: | rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
rotation/seculr/diffuse_composition.o: | numerics/numerics_lib.o rotation/rotation_scratch_lib.o state/star_info_lib.o
rotation/seculr/diffuse_composition_driver.o: | state/star_info_lib.o
rotation/seculr/diffusion_velocity_scales.o: | rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
rotation/seculr/equal_grid_to_model.o: | numerics/numerics_lib.o rotation/rotation_scratch_lib.o state/star_info_lib.o
rotation/seculr/secular_transport.o: | numerics/numerics_lib.o rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
rotation/seculr/zahn_coupling_factor.o: | rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
rotation/shape/equipotential_integrand.o: | state/phys_const_lib.o state/star_info_lib.o
rotation/shape/rotation_shape_factors.o: | numerics/numerics_lib.o rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
rotation/shape/shape.o: | state/phys_const_lib.o state/star_info_lib.o
rotation/shape/shell_inertia_integral.o: | state/phys_const_lib.o
rotation/shape/zone_moments_of_inertia.o: | state/phys_const_lib.o state/star_info_lib.o
rotation/solid_body_omega.o: | rotation/rotation_scratch_lib.o state/star_info_lib.o
rotation/viscos.o: | state/phys_const_lib.o state/star_info_lib.o
setup/henyey_eliminate.o: | state/phys_const_lib.o state/star_info_lib.o
setup/locate_shell_boundaries.o: | state/star_info_lib.o
setup/map_user_inputs.o: | io/controls_lib.o state/star_info_lib.o
setup/mid_timestep_model.o: | core/burn_lib.o net/net_lib.o rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
setup/rescale_model.o: | eos/eos_lib.o io/luout_lib.o state/phys_const_lib.o state/star_info_lib.o
setup/rezone.o: | io/luout_lib.o io/run_log.o kap/kap_lib.o numerics/numerics_lib.o rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
setup/rotation_stability_setup.o: | rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
setup/setup_solar_calibration.o: | state/star_info_lib.o
setup/setup_star_calibration.o: | io/luout_lib.o state/phys_const_lib.o state/star_info_lib.o
setup/setups.o: | atm/atm_lib.o atm/atm_table_lib.o eos/eos_lib.o eos/yale_eos_lib.o kap/kap_lib.o state/phys_const_lib.o state/star_info_lib.o
state/controls_sync_lib.o: | io/controls_lib.o state/star_info_lib.o
util/compute_timestep.o: | state/phys_const_lib.o state/star_info_lib.o
util/timestep_limit_hburn.o: | core/burn_lib.o net/net_lib.o state/phys_const_lib.o state/star_info_lib.o
util/timestep_limit_heburn.o: | core/burn_lib.o net/net_lib.o state/star_info_lib.o
util/timestep_limit_hr.o: | state/star_info_lib.o
util/timestep_limit_omega.o: | state/star_info_lib.o
util/timestep_limit_structure.o: | state/star_info_lib.o
util/version.o: | state/phys_const_lib.o
wind/kawaler_wind.o: | state/phys_const_lib.o state/star_info_lib.o
wind/massloss.o: | atm/atm_lib.o atm/atm_table_lib.o eos/eos_lib.o rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
wind/matt_structure_factor.o: | state/phys_const_lib.o state/star_info_lib.o
wind/matt_wind.o: | state/phys_const_lib.o state/star_info_lib.o
wind/mdot.o: | rotation/rotation_scratch_lib.o state/phys_const_lib.o state/star_info_lib.o
wind/wcz.o: | state/phys_const_lib.o state/star_info_lib.o
wind/wind_spindown.o: | state/phys_const_lib.o state/star_info_lib.o
wind/wind_spindown_matt.o: | state/phys_const_lib.o state/star_info_lib.o

# real prerequisites: include files
io/read_controls.o: io/inlist_new_decl.inc io/inlist_new_read.inc
state/star_info_lib.o: state/controls_state_def.inc state/job_controls_def.inc
