#!/usr/bin/env python3
"""Generate src/deps.mk: Fortran module and include dependencies.

GNU Make has no Fortran module scanning, and the hand-maintained
MODULE_SRCS list + order-only rules caused three stale-.mod incidents
in one week (a module object compiled against a stale surviving .mod
bakes wrong derived-type offsets into the object SILENTLY -- see the
Makefile's clean-target comment). This generator removes the human
from the loop:

  * scans every src/**/*.f90 for `module <name>` definitions and
    `use <name>` references (modules defined in-repo only);
  * emits MODULE_SRCS (every module-defining file);
  * emits a REAL prerequisite for EVERY object on the .mod files of
    the modules it uses, plus a `<mod>.mod: <definer>.o` rule with an
    empty recipe (the classic gfortran+make idiom). This fixes BOTH
    failure modes: build order under -j, and staleness -- when a
    module's interface changes, gfortran rewrites the .mod and every
    consumer recompiles; when it doesn't, gfortran leaves the .mod
    untouched and nothing rebuilds spuriously. (Order-only rules
    alone fixed only the first: a changed optional-argument interface
    left stale caller objects passing the old ABI -- a segfault.);
  * emits real prerequisites for `include '<file>.inc'` lines
    (resolved relative to the source's directory, gfortran's own
    search rule), so editing a generated .inc rebuilds its includer.

Test-program objects (*/test/*.f90) get rules too -- they build via
their own targets but obey the same module ordering.

Usage:
  python3 tools/gen_makefile_deps.py           # (re)write src/deps.mk
  python3 tools/gen_makefile_deps.py --check   # exit 1 if stale (CI)
"""
import pathlib
import re
import sys

SRC = pathlib.Path(__file__).resolve().parent.parent
OUT = SRC / "deps.mk"

MODULE_RE = re.compile(r"^\s*module\s+([a-z]\w*)\s*$", re.I | re.M)
USE_RE = re.compile(r"^\s*use\s+([a-z]\w*)", re.I | re.M)
INC_RE = re.compile(r"^\s*include\s+'([^']+)'", re.I | re.M)


def strip_comments(text):
    return "\n".join(l.split("!")[0] for l in text.splitlines())


def main():
    sources = sorted(p for p in SRC.rglob("*.f90"))
    mod_of = {}          # module name -> defining source (relative)
    uses = {}            # relative source -> set of used module names
    incs = {}            # relative source -> list of include prereqs
    for p in sources:
        rel = p.relative_to(SRC).as_posix()
        text = strip_comments(p.read_text(errors="replace"))
        for m in MODULE_RE.finditer(text):
            name = m.group(1).lower()
            if name != "procedure":
                mod_of[name] = rel
        uses[rel] = {u.group(1).lower() for u in USE_RE.finditer(text)}
        found = []
        for i in INC_RE.finditer(text):
            cand = (p.parent / i.group(1))
            if cand.is_file():
                found.append(cand.relative_to(SRC).as_posix())
        if found:
            incs[rel] = found

    lines = [
        "# GENERATED by tools/gen_makefile_deps.py -- do not edit by hand.",
        "# Regenerate after adding/removing a module, a use statement, or",
        "# an include. CI runs the generator with --check.",
        "",
        "MODULE_SRCS := " + " ".join(sorted(set(mod_of.values()))),
        "",
        "# each .mod file is produced by compiling its definer; the empty",
        "# recipe lets make order and compare against the .mod timestamp",
        "# (gfortran only rewrites a .mod whose content changed, so",
        "# consumers rebuild exactly when an interface changes)",
    ]
    for name in sorted(mod_of):
        lines.append(f"{name}.mod: {mod_of[name][:-4]}.o")
        lines.append("\t@true")
    lines += ["", "# real prerequisites: each object depends on the .mod",
              "# files of every module it uses"]
    for rel in sorted(uses):
        deps = sorted({u for u in uses[rel]
                       if u in mod_of and mod_of[u] != rel})
        if deps:
            mods = " ".join(d + ".mod" for d in deps)
            lines.append(f"{rel[:-4]}.o: {mods}")
    lines += ["", "# real prerequisites: include files"]
    for rel in sorted(incs):
        lines.append(f"{rel[:-4]}.o: " + " ".join(sorted(set(incs[rel]))))
    content = "\n".join(lines) + "\n"

    if "--check" in sys.argv:
        if not OUT.is_file() or OUT.read_text() != content:
            print("deps.mk is stale: rerun tools/gen_makefile_deps.py",
                  file=sys.stderr)
            sys.exit(1)
        print("deps.mk up to date")
        return
    OUT.write_text(content)
    print(f"{len(mod_of)} modules, {sum(1 for r in uses if uses[r] & set(mod_of))} "
          f"dependent sources -> deps.mk")


if __name__ == "__main__":
    main()
