#!/usr/bin/env python3
"""Generate the new-style inlist reader + .defaults docs from the registry.

Source of truth: defaults/controls_registry.tsv. Emits:
  core/inlist_new_decl.inc  -- declarations of new-name variables that do
                               not already exist in parmin's scope, plus
                               the &star_job / &controls namelist groups
  core/inlist_new_read.inc  -- the new-style read: seed new names from
                               the legacy defaults already assigned by
                               parmin, read the two groups (one file or
                               two), then map back onto the legacy names
                               so ALL downstream code is untouched
  defaults/star_job.defaults, defaults/controls.defaults -- documentation

Entry classes (per row): keep (new == legacy: the legacy variable itself
joins the new group), direct (new == the canonical internal name parmin
already copies into post-read: that variable joins the group), newlocal
(a fresh local is declared). Rows with status 'unused' are dead legacy
controls: accepted by the legacy path only.

Defaults strategy: the generated code NEVER re-states default values.
Pre-read it seeds every new-style variable from its legacy twin (which
parmin has already defaulted); post-read it copies back. Defaults thus
stay defined in exactly one place (parmin + -finit-local-zero) and the
two paths agree by construction.
"""
import pathlib
import re
import sys

SRC = pathlib.Path(__file__).resolve().parent.parent
REG = SRC / "defaults" / "controls_registry.tsv"


def joined_decl_lines(text):
    out, buf = [], ""
    for l in text.splitlines():
        c = l.split("!")[0]
        buf = (buf + " " + c.strip().lstrip("&")) if buf else c
        if c.rstrip().endswith("&"):
            buf = buf.rstrip().rstrip("&")
            continue
        out.append(buf)
        buf = ""
    return out


def legacy_decl(name, decl_lines):
    """Return (type_spec, dims) for a legacy namelist variable."""
    for c in decl_lines:
        lc = c.lower()
        if "::" not in lc:
            continue
        typ, rest = lc.split("::", 1)
        for g in re.split(r",(?![^()]*\))", rest):
            m = re.match(r"\s*([a-z][a-z0-9_]*)\s*(\(([^)]*)\))?", g)
            if m and m.group(1) == name:
                return typ.strip(), (m.group(3) or "")
    return None, None


def main():
    rows = []
    for l in REG.read_text().splitlines()[1:]:
        parts = l.split("\t")
        rows.append(dict(group=parts[0], legacy=parts[1], typ=parts[2],
                         default=parts[3], new=parts[4], status=parts[5],
                         mesa=parts[6], doc=parts[7] if len(parts) > 7 else ""))
    parmin = (SRC / "io" / "parmin.f90").read_text()
    decls = joined_decl_lines(parmin)
    for extra in ("const/controls_lib.f90", "state/phys_const_lib.f90",
                  "const/const_lib.f90", "const/intpar_lib.f90",
                  "kap/opacity_table_lib.f90"):
        decls += joined_decl_lines((SRC / extra).read_text())
    # canonical names = simple post-read copies canon = legacy
    canon = {}
    for c in joined_decl_lines(parmin):
        m = re.match(r"^\s*([a-z]\w*)\s*=\s*([a-z]\w*)\s*$", c, re.I)
        if m:
            canon.setdefault(m.group(2).lower(), m.group(1).lower())

    live = [r for r in rows if r["status"] != "unused"]
    for r in live:
        if r["new"] == r["legacy"]:
            r["cls"] = "keep"
        elif canon.get(r["legacy"]) == r["new"]:
            r["cls"] = "direct"
        else:
            r["cls"] = "newlocal"

    # ---- declarations ----
    decl = ["! GENERATED by tools/gen_inlist.py from defaults/controls_registry.tsv",
            "! -- do not edit by hand. New-style inlist (&star_job/&controls)",
            "! variables that have no existing symbol in parmin's scope, plus",
            "! the two namelist groups. See defaults/*.defaults for docs."]
    for r in live:
        if r["cls"] != "newlocal":
            continue
        typ, dims = legacy_decl(r["legacy"], decls)
        if typ is None:
            print("WARNING: no legacy declaration found for", r["legacy"])
            typ, dims = "double precision", ""
        d = f"({dims})" if dims else ""
        decl.append(f"      {typ} :: {r['new']}{d}")
    for grp, gname in (("control", "star_job"), ("physics", "controls")):
        members = [r["new"] if r["cls"] != "keep" else r["legacy"]
                   for r in live if r["group"] == grp]
        decl.append(f"      namelist /{gname}/ &")
        line = "           & "
        outl = []
        for i, mname in enumerate(members):
            piece = mname + ("," if i < len(members) - 1 else "")
            if len(line) + len(piece) > 72:
                outl.append(line.rstrip() + " &")
                line = "           & "
            line += piece + " "
        outl.append(line.rstrip())
        decl.extend(outl)
    (SRC / "io" / "inlist_new_decl.inc").write_text("\n".join(decl) + "\n")

    # ---- read block ----
    rd = ["! GENERATED by tools/gen_inlist.py -- do not edit by hand.",
          "! New-style inlist read. Runs INSTEAD of the legacy",
          "! &control/&physics read; parmin's own default assignments have",
          "! already run, so seeding new names from legacy twins reproduces",
          "! the exact legacy defaults, and the post-read copies hand the",
          "! user's values back to the legacy names all downstream code",
          "! (including parmin's own post-processing) reads.",
          "! Seed new-style names from the legacy defaults:"]
    for r in live:
        if r["cls"] == "keep":
            continue
        rd.append(f"      {r['new']} = {r['legacy']}")
    rd += [
        "! Read &star_job from the first file.",
        "      open(unit=standard_unit, file=control_nml_file, status='OLD')",
        "      read(unit=standard_unit, nml=star_job)",
        "! &controls may live in the same file (single-inlist style) or in",
        "! the second file (paired style).",
        "      if (nml_file_has_group(control_nml_file, 'controls')) then",
        "         rewind(standard_unit)",
        "         read(unit=standard_unit, nml=controls)",
        "         close(standard_unit)",
        "      else",
        "         close(standard_unit)",
        "         open(unit=run_unit, file=physics_nml_file, status='OLD')",
        "         read(unit=run_unit, nml=controls)",
        "         close(run_unit)",
        "      end if",
        "! Map the new-style values back onto the legacy names:",
    ]
    for r in live:
        if r["cls"] == "keep":
            continue
        rd.append(f"      {r['legacy']} = {r['new']}")
    (SRC / "io" / "inlist_new_read.inc").write_text("\n".join(rd) + "\n")

    # ---- defaults docs ----
    for grp, gname in (("control", "star_job"), ("physics", "controls")):
        out = [f"! {gname}.defaults -- every &{gname} control with its default.",
               "! GENERATED by tools/gen_inlist.py from",
               "! defaults/controls_registry.tsv (edit that, then regenerate).",
               "! Defaults marked (implicit) are static zero/false/'' --",
               "! no explicit assignment exists; pinned by -finit-local-zero.",
               "", f"&{gname}", ""]
        for r in live:
            if r["group"] != grp:
                continue
            name = r["new"] if r["cls"] != "keep" else r["legacy"]
            if r["doc"]:
                out.append(f"      ! {r['doc']}")
            if r["legacy"] != name:
                out.append(f"      ! (legacy name: {r['legacy']})")
            d = r["default"]
            implicit = d.endswith("*")
            d = d.rstrip("*") or "?"
            out.append(f"      {name} = {d}" + ("   ! (implicit)" if implicit else ""))
            out.append("")
        out += ["/", ""]
        dead = [r for r in rows if r["status"] == "unused" and r["group"] == grp]
        if dead:
            out.append("! Unused legacy controls (accepted by the legacy reader only,")
            out.append("! referenced nowhere in the code; dropped from the new format):")
            out.append("!   " + ", ".join(r["legacy"] for r in dead))
        (SRC / "defaults" / f"{gname}.defaults").write_text("\n".join(out) + "\n")

    print(f"live: {len(live)} (keep {sum(r['cls']=='keep' for r in live)}, "
          f"direct {sum(r['cls']=='direct' for r in live)}, "
          f"newlocal {sum(r['cls']=='newlocal' for r in live)}); "
          f"dead: {len(rows)-len(live)}")


if __name__ == "__main__":
    main()
