#!/usr/bin/env python3
"""Generate star%ctrl's type body and the buffer sync module.

Source of truth: const/controls_lib.f90's declarations (names, types,
dims, and declaration-time defaults -- the same single place the
legacy read has always taken its pristine state from). Emits:

  state/controls_state_def.inc  -- the component list of the
      controls_state type (star_info_lib defines
      `type, public :: controls_state` around an include of this
      file). Every component gets a default initializer: the
      buffer's own where it has one, otherwise the explicit
      zero/blank/.false. that static module storage gave it -- so
      `star%ctrl = controls_state()` reproduces the pristine
      pre-parmin state exactly.

  state/controls_sync_lib.f90   -- module controls_sync_lib with
      seed_controls_buffer  (buffer member = star%ctrl%member) and
      store_controls_to_star (star%ctrl%member = buffer member),
      one assignment per member, in declaration order.

Regenerate (and commit the results) whenever controls_lib's member
list changes:  python3 tools/gen_controls_state.py
The build breaks loudly on drift (unknown/missing components).
"""
import pathlib
import re

SRC = pathlib.Path(__file__).resolve().parent.parent
LIB = SRC / "const" / "controls_lib.f90"
DEF = SRC / "state" / "controls_state_def.inc"
SYNC = SRC / "state" / "controls_sync_lib.f90"

TYPE_RE = re.compile(
    r"^\s*(double precision|integer|logical|character\s*\(\s*len\s*=\s*\d+\s*\))"
    r"\s*(,\s*public)?\s*::\s*(.*)$",
    re.IGNORECASE,
)

ZERO = {
    "double precision": "0.0d0",
    "integer": "0",
    "logical": ".false.",
    "character": "' '",
}


def joined_decl_lines(text):
    """Join &-continued lines, strip comments."""
    out, buf = [], ""
    for raw in text.splitlines():
        code = raw.split("!")[0]
        if buf:
            code = code.lstrip().lstrip("&")
        buf += code
        if buf.rstrip().endswith("&"):
            buf = buf.rstrip()[:-1]
            continue
        if buf.strip():
            out.append(buf)
        buf = ""
    return out


def split_entities(s):
    """Split a declaration's entity list on top-level commas."""
    ents, depth, cur = [], 0, ""
    for ch in s:
        if ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        if ch == "," and depth == 0:
            ents.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        ents.append(cur.strip())
    return ents


def parse():
    members = []  # (typespec, name, dims, init)
    for line in joined_decl_lines(LIB.read_text()):
        m = TYPE_RE.match(line)
        if not m:
            continue
        typespec = re.sub(r"\s+", " ", m.group(1).lower()).replace(" (", "(")
        for ent in split_entities(m.group(3)):
            em = re.match(r"^(\w+)\s*(\([^)]*\))?\s*(=\s*(.*))?$", ent, re.S)
            if not em:
                raise SystemExit(f"cannot parse entity: {ent!r}")
            name, dims, init = em.group(1), em.group(2) or "", em.group(4)
            if init is None:
                base = "character" if typespec.startswith("character") else typespec
                init = ZERO[base]
            members.append((typespec, name, dims, init.strip()))
    if not members:
        raise SystemExit("no members parsed from controls_lib.f90")
    return members


def main():
    members = parse()
    with DEF.open("w") as f:
        f.write(
            "! GENERATED by tools/gen_controls_state.py from\n"
            "! const/controls_lib.f90 -- do not edit; regenerate instead.\n"
            "! One component per buffer member, declaration order, every\n"
            "! one default-initialized (see the generator's header).\n"
        )
        for typespec, name, dims, init in members:
            f.write(f"            {typespec} :: {name}{dims} = {init}\n")
    with SYNC.open("w") as f:
        f.write(
            "!----------------------------------------------------------------------\n"
            "! controls_sync_lib\n"
            "!----------------------------------------------------------------------\n"
            "! GENERATED by tools/gen_controls_state.py from\n"
            "! const/controls_lib.f90 -- do not edit; regenerate instead.\n"
            "! The two copies between parmin's namelist read BUFFER\n"
            "! (controls_lib's module variables) and the authoritative\n"
            "! star%ctrl. read_controls drives the sequence:\n"
            "!   star%ctrl = controls_state()   (pristine defaults)\n"
            "!   call seed_controls_buffer      (buffer <- star%ctrl)\n"
            "!   call parmin(...)               (namelist reads over buffer)\n"
            "!   call store_controls_to_star    (star%ctrl <- buffer)\n"
            "module controls_sync_lib\n"
            "      use controls_lib\n"
            "      use star_info_lib, only: star\n"
            "      implicit none\n"
            "\n"
            "contains\n"
            "\n"
            "subroutine seed_controls_buffer\n"
        )
        for _, name, _, _ in members:
            f.write(f"      {name} = star%ctrl%{name}\n")
        f.write(
            "end subroutine seed_controls_buffer\n"
            "\n"
            "subroutine store_controls_to_star\n"
        )
        for _, name, _, _ in members:
            f.write(f"      star%ctrl%{name} = {name}\n")
        f.write(
            "end subroutine store_controls_to_star\n"
            "\n"
            "end module controls_sync_lib\n"
        )
    print(f"{len(members)} members -> {DEF.name}, {SYNC.name}")


if __name__ == "__main__":
    main()
