#!/usr/bin/env python3
"""Generate src/io/default_columns.inc from defaults/*_columns.list.

defaults/history_columns.list and defaults/profile_columns.list are
the AUTHORITY on the default output column selection: a blank
history_columns_file / profile_columns_file control selects exactly
the uncommented names in these files, in file order. Opt-in columns
ship commented out ('!' immediately followed by the name); remove
the '!' and rebuild (the Makefile reruns this generator when a .list
changes) to add one to the default output.

The selection is compiled in rather than read at runtime so a run
never depends on locating the source tree from its working
directory (the {YREC_INPUT}-style relative fallback has a history of
breaking) and a deployed bare binary keeps working.

test_mesa_output.py::test_default_columns_lists_in_sync holds the
.list files to the writers' column tables and runs --check.

Usage:
  python3 tools/gen_default_columns.py           # (re)write the .inc
  python3 tools/gen_default_columns.py --check   # exit 1 if stale (CI)
"""
import pathlib
import sys

SRC = pathlib.Path(__file__).resolve().parent.parent
OUT = SRC / "io" / "default_columns.inc"
WIDTH = 24  # matches the writers' character(len=24) name tables


def names_from(fname):
    out = []
    for line in (SRC / "defaults" / fname).read_text().splitlines():
        line = line.split("!")[0].strip()
        if line:
            if len(line) > WIDTH:
                sys.exit(f"{fname}: '{line}' longer than {WIDTH} chars")
            out.append(line)
    return out


def emit(tag, names):
    lines = [f"      integer, parameter :: n_{tag}_default = {len(names)}",
             f"      character(len={WIDTH}), parameter :: "
             f"{tag}_default_names(n_{tag}_default) = [ &"]
    for i, n in enumerate(names):
        sep = ", &" if i < len(names) - 1 else " ]"
        lines.append(f"           '{n:<{WIDTH}}'{sep}")
    return lines


def main():
    lines = [
        "! GENERATED by tools/gen_default_columns.py from",
        "! defaults/history_columns.list and",
        "! defaults/profile_columns.list -- do not edit; edit the .list",
        "! files and rebuild (make reruns the generator). These are the",
        "! default output column selections used when",
        "! history_columns_file / profile_columns_file are blank.",
    ]
    hist = names_from("history_columns.list")
    prof = names_from("profile_columns.list")
    lines += emit("hist", hist)
    lines += emit("prof", prof)
    content = "\n".join(lines) + "\n"

    if "--check" in sys.argv:
        if not OUT.is_file() or OUT.read_text() != content:
            print("default_columns.inc is stale: rerun "
                  "tools/gen_default_columns.py", file=sys.stderr)
            sys.exit(1)
        print("default_columns.inc up to date")
        return
    OUT.write_text(content)
    print(f"{len(hist)} history + {len(prof)} profile default columns "
          "-> io/default_columns.inc")


if __name__ == "__main__":
    main()
